In [ ]:
NumPy =====> Numerical python 

In [3]:
import numpy as np

In [5]:
array_1 = np.array([1,2,3])

array([1, 2, 3])

In [9]:
array_2 = np.array([[1,2,3],[4,5,6]])
print(array_2)

[[1 2 3]
 [4 5 6]]


In [11]:
arra3 = np.array((3,5,4))

In [13]:
print(arra3)

[3 5 4]


# conversion of datatypes within the array,list

In [17]:
np.array([1,2,3],dtype="complex")

array([1.+0.j, 2.+0.j, 3.+0.j])

In [19]:
np.array([1,2,3],dtype="float")

array([1., 2., 3.])

# DIFFERENCE BETWEEN NUMPY ARRAY AND LIST

In [24]:
array_01 = np.array([1,2,3])

In [26]:
array_02 = np.array([2,3,4])

In [28]:
print(array_01 + array_02)

[3 5 7]


In [30]:
list_1 = [1,2,3]
list_2 = [2,3,4]

In [36]:
#concates the lists
print(list_1 + list_2)

[1, 2, 3, 2, 3, 4]


In [40]:
#for performing the operation we have to 
list_ans = []
for i,j in zip(list_1,list_2):
    list_ans.append(i+j)
print(list_ans)
    

[3, 5, 7]


-Numpy array have fixed size of array creation, but it is not the case with pyhon lists

-the elements in numpy array are all required to be of same datatype,list can support all data types at a time 

-Numpy takes less time consuming while performing math operations, lists take time.

-numpy arrays takes less space as compared to the lists


In [43]:
#to check the dimension of an array
array_01.ndim

1

In [49]:
array_2.ndim

2

In [51]:
#to check the shape of the matrix
array_01.shape

(3,)

In [53]:
array_2.shape

(2, 3)

In [55]:
#to check size of the array (number of elemtns)
array_2.size


6

## Array Atributes

In [62]:
#arange => same as range in lists, in numpy it prints the values in the specified range
a1 = np.arange(10)
a2 = np.arange(30,40)
print(a1)
print(a2)

[0 1 2 3 4 5 6 7 8 9]
[30 31 32 33 34 35 36 37 38 39]


In [66]:
a3 = np.arange(12,dtype="float")
print(a3)

[ 0.  1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11.]


In [70]:
#to convert 1D to 2D we use .reshape(row,coloumn)
a3 = np.arange(12,dtype="float").reshape(4,3)
print(a3)

[[ 0.  1.  2.]
 [ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9. 10. 11.]]


In [76]:
#to convert the datatype of an array we use .astype(np.datatype)
a3 = a3.astype(np.int64)
print(a3)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [78]:
a3*2

array([[ 0,  2,  4],
       [ 6,  8, 10],
       [12, 14, 16],
       [18, 20, 22]], dtype=int64)

In [80]:
for i in a3:
    print(i)

[0 1 2]
[3 4 5]
[6 7 8]
[ 9 10 11]


In [82]:
#to pick specific elemts we use np.nditer(array)
for i in np.nditer(a3):
    print(i)

0
1
2
3
4
5
6
7
8
9
10
11


In [84]:
a3>5

array([[False, False, False],
       [False, False, False],
       [ True,  True,  True],
       [ True,  True,  True]])

# DIFFERENT WAYS OF CREATING A  NUMPY ARRAY

In [89]:
import numpy as np

In [93]:
z1 = np.array([10,11,12])
print(z1)

[10 11 12]


In [95]:
z1 = np.array([[10,11,12],[13,14,15]])
print(z1)

[[10 11 12]
 [13 14 15]]


In [105]:
#array of zeros: 
c1 = np.zeros((3,3),dtype="int")
c1

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [107]:
#array of ones: 
c2 = np.ones((3,3),dtype="int")
c2

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [123]:
#array of randoms
c3 = np.random.rand(4,4)
c3

array([[0.0089861 , 0.38657128, 0.04416006, 0.95665297],
       [0.43614665, 0.94897731, 0.78630599, 0.8662893 ],
       [0.17316542, 0.07494859, 0.60074272, 0.16797218],
       [0.73338017, 0.40844386, 0.52790882, 0.93757158]])

In [134]:
#to fix the randomness of an array we use np.random.seed in the same cell above the array
np.random.seed(4)
c3 = np.random.rand(4,4)
c3

array([[0.96702984, 0.54723225, 0.97268436, 0.71481599],
       [0.69772882, 0.2160895 , 0.97627445, 0.00623026],
       [0.25298236, 0.43479153, 0.77938292, 0.19768507],
       [0.86299324, 0.98340068, 0.16384224, 0.59733394]])

In [136]:
#for array with negative values aswell we use np.random.randn
c4 = np.random.randn(3,3)
c4

array([[ 0.61866969, -0.08798693,  0.4250724 ],
       [ 0.33225315, -1.15681626,  0.35099715],
       [-0.60688728,  1.54697933,  0.72334161]])

In [144]:
np.random.seed(4)
c5 = np.random.randint(low = 50,high =100,size=(3,3))
c5

array([[96, 55, 51],
       [90, 73, 58],
       [59, 89, 95]])

# SLICING AND INDEXING

In [146]:
#[row,coloumn]
c5[1,1]

73

In [148]:
#suppose we need to fetch 96,55,90,73:
c5[0:2,0:2]

array([[96, 55],
       [90, 73]])

In [154]:
c5[2,1:]

array([89, 95])

In [162]:
c5[1:,0:2]

array([[90, 73],
       [59, 89]])

# MANIPULATION

In [165]:
#TO CONVERT 1D TO 2D WE USE reshape(row,coloumn)
G = np.arange(1,13).reshape(3,4)

In [169]:
G


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [175]:
# TO CONVERT 2D ARRAY TO 1D OR TO FLATTEN WE USE araay.ravel()
g = G.ravel()
g

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [179]:
#to transpose or to make row to coloumn values and vice versa we use array.transpose() 
T = G.transpose()
T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

# stacking and splitting of matrix

In [182]:
#we can stack the matrix one on top the other vertically or horizontally
#  vertical = vstack
#  horizontal = hstack

In [190]:
mat_1 = np.arange(12).reshape(3,4)
mat_2 = np.arange(12,24).reshape(3,4)

In [192]:
mat_1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [194]:
mat_2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [210]:
h = np.hstack((mat_1,mat_2))
h

array([[ 0,  1,  2,  3, 12, 13, 14, 15],
       [ 4,  5,  6,  7, 16, 17, 18, 19],
       [ 8,  9, 10, 11, 20, 21, 22, 23]])

In [212]:
v = np.vstack((mat_1,mat_2))
v

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [214]:
#we can also perform splitting 
#with np.vsplit or hsplit but it should be equal amounts of split in matrix 
# np.vsplit(array,number of parts split)

np.vsplit(v,2)

[array([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]]),
 array([[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]])]

In [218]:
np.hsplit(h,4)

[array([[0, 1],
        [4, 5],
        [8, 9]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11]]),
 array([[12, 13],
        [16, 17],
        [20, 21]]),
 array([[14, 15],
        [18, 19],
        [22, 23]])]

In [15]:
#using list or tuples

import numpy as np

lst = [10,20,30]
my_array = np.array(lst)
my_array

array([10, 20, 30])

In [11]:
my_array1 = np.array([10,20,30])
my_array1


array([10, 20, 30])

In [21]:
tpl = (50,333,3535)
my_tpl = np.array(tpl)
my_tpl

array([  50,  333, 3535])

In [23]:
#linear algebra operations

arr1 = np.array([2,3,4,5])
arr2 = np.array([8,9,10,11])

arr = np.dot(arr1, arr2)
arr

#(2*8 + 3*9 + 4*10 + 5*11)

138